In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
df = pd.read_csv("Advertising.csv")

In [57]:
X = df.drop('sales', axis=1)

In [58]:
y = df['sales']

In [59]:
from sklearn.preprocessing import PolynomialFeatures

In [60]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [61]:
poly_features = polynomial_converter.fit_transform(X)

In [85]:
#X.shape

In [86]:
#poly_features.shape

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [89]:
#X_train.shape

In [90]:
from sklearn.preprocessing import StandardScaler

In [91]:
scaler = StandardScaler()

In [92]:
scaler.fit(X_train)

StandardScaler()

In [93]:
X_train = scaler.transform(X_train)

In [94]:
X_test = scaler.transform(X_test)

In [95]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [96]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [97]:
from sklearn.linear_model import Ridge

In [98]:
ridge_model = Ridge(alpha=10)

In [99]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [100]:
test_predictions = ridge_model.predict(X_test)

In [101]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [102]:
MAE = mean_absolute_error(y_test, test_predictions)

In [103]:
MAE

0.5774404204714175

In [104]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [105]:
RMSE

0.8946386461319681

In [106]:
from sklearn.linear_model import RidgeCV

In [114]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [115]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [116]:
ridge_cv_model.alpha_

0.1

In [118]:
#from sklearn.metrics import SCORERS

In [119]:
#SCORERS.keys()

In [120]:
test_predictions = ridge_cv_model.predict(X_test)

In [121]:
MAE = mean_absolute_error(y_test, test_predictions)

In [122]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [123]:
MAE

0.42737748843675194

In [124]:
RMSE

0.6180719926956963

In [125]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [126]:
ridge_cv_model.best_score_

-0.3749223340292957

In [129]:
from sklearn.linear_model import LassoCV

In [134]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)

In [135]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [136]:
lasso_cv_model.alpha_

0.4943070909225828

In [137]:
test_predictions = lasso_cv_model.predict(X_test)

In [139]:
MAE = mean_absolute_error(y_test, test_predictions)

In [140]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [141]:
MAE

0.6541723161252856

In [142]:
RMSE

1.1308001022762535

In [144]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [147]:
from sklearn.linear_model import ElasticNetCV

In [152]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=1000000)

In [153]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [155]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [156]:
elastic_model.l1_ratio_

1.0

In [157]:
elastic_model.alpha_

0.004943070909225827

In [158]:
lasso_cv_model.alpha_

0.4943070909225828

In [160]:
test_predictions = elastic_model.predict(X_test)

In [161]:
MAE = mean_absolute_error(y_test, test_predictions)

In [162]:
MAE

0.4335034618590069