In [1]:
text = ['This is a line', 
        'This is another line',
        'Completely different line']

In [15]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [18]:
cv = CountVectorizer()

In [19]:
cv.fit_transform(text) #return sparse matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [20]:
sparse_matrix = cv.fit_transform(text)

In [21]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [22]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [23]:
tfidf = TfidfTransformer()

In [24]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [26]:
results = tfidf.fit_transform(sparse_matrix) #BOW ---> TF-IDF

In [28]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
tv = TfidfVectorizer()

In [31]:
tv_results = tv.fit_transform(text)

In [32]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])