In [1]:
import numpy as np

In [2]:
mylist=[1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
myarr=np.array(mylist)

In [5]:
myarr

array([1, 2, 3])

In [6]:
type(myarr)

numpy.ndarray

In [7]:
mymatrix=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
myarrmatrix=np.array(mymatrix)

In [10]:
myarrmatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5) #for 1D array

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5, 5)) #for 2D array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,11) #return evenly spaced numbers over a specified interval

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.linspace(0,10,13) #it includes end points

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        ])

In [19]:
len(np.linspace(0, 5, 25))

25

In [20]:
np.eye(5) #makes an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(1)

array([0.65005872])

In [24]:
np.random.rand(3, 4)

array([[0.44998701, 0.7817626 , 0.82459094, 0.35532025],
       [0.47337317, 0.87904998, 0.1102983 , 0.9362671 ],
       [0.87252148, 0.28931679, 0.77358782, 0.78157406]])

In [26]:
np.random.randn(5) #create samples

array([-0.59123991, -1.99319547,  1.58504488,  1.09945643,  1.33809768])

In [27]:
np.random.randn(4, 5)

array([[ 1.02170208,  0.57546614, -0.37604208, -0.70055329, -0.60887378],
       [ 0.83013694, -1.2323516 ,  0.06727942,  1.09917134,  0.79410446],
       [-1.42689644, -0.29062596,  1.32280621,  0.84983565, -1.18574992],
       [-0.84394626, -0.18645095,  0.07704435,  0.63310976,  0.99810217]])

In [31]:
np.random.randint(0, 101, 5) #return random integers #for 1D array

array([98, 31, 76, 65, 22])

In [32]:
np.random.randint(0, 101, (4,5)) #for 2D array

array([[ 9, 46, 23, 82, 45],
       [89, 72, 69, 67, 33],
       [86, 39, 57, 74, 26],
       [80, 82,  9, 76, 54]])

In [33]:
np.random.seed(42) #set a particular set of random numbersarr=
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr=np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr=np.random.randint(0, 101, 10)

In [39]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [40]:
ranarr.max()

99

In [41]:
ranarr.argmax() #return index location of maximum element

5

In [42]:
ranarr.argmin()

7

In [43]:
ranarr.dtype()

TypeError: 'numpy.dtypes.Int32DType' object is not callable

In [44]:
ranarr.dtype #of how many bits

dtype('int32')

In [45]:
arr.shape

(25,)

In [46]:
arr=arr.reshape(5,5)

In [47]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.shape

(5, 5)

In [50]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [51]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [53]:
arr=np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[8]

8

In [56]:
arr[1:5]

array([1, 2, 3, 4])

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
arr[0:5]=100

In [61]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [81]:
arr=np.arange(0,11)

In [82]:
slice_of_arr=arr[0:5]

In [83]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [84]:
b=arr[0:5]

In [85]:
b

array([0, 1, 2, 3, 4])

In [86]:
b[:]=99

In [87]:
b

array([99, 99, 99, 99, 99])

In [88]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [89]:
arr_copy=arr.copy()

In [90]:
arr_copy[:]=100

In [91]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [92]:
arr_2d=np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [93]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [94]:
arr_2d.shape #no of rows and no of columns

(3, 3)

In [95]:
arr_2d[0]

array([ 5, 10, 15])

In [98]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [99]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [100]:
arr=np.arange(1, 11)

In [101]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [103]:
bool_arr=arr>4

In [104]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [105]:
arr[bool_arr] #return which is true

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [107]:
arr=np.arange(0, 10)

In [108]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [111]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [112]:
2*arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [113]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [114]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [116]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
1/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_1540\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [118]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [119]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [120]:
np.log(arr)

C:\Users\HP\AppData\Local\Temp\ipykernel_1540\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [121]:
arr.sum()

45

In [122]:
arr.mean()

4.5

In [123]:
arr.max()

9

In [124]:
arr.var()

8.25

In [125]:
arr.std()

2.8722813232690143

In [127]:
arr2d=np.arange(0, 25).reshape(5,5)

In [128]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [129]:
arr2d.sum()

300

In [130]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [131]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])